import { masterShops } from "../config/shops";
import type { InventoryBook } from "./types";

export const demoInventory: InventoryBook[] = [
  {
    inventoryId: 1,
    isbn13: "9780571364909",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    publisher: "Faber & Faber",
    publishedYear: 2021,
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780571364909-L.jpg",
    format: "Paperback",
    subjects: ["Fiction", "Literary"],
    shop: masterShops[0],
    shelfLocation: "Fiction · I–K · Shelf 3",
    condition: "good",
    pricePence: 350,
    valuationConfidence: "high",
    valuationReasons: ["Recent popular fiction", "Good condition"],
    scannedAt: "2026-07-23T08:42:00Z",
  },
  {
    inventoryId: 2,
    isbn13: "9781784702861",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    publisher: "Vintage",
    publishedYear: 2015,
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781784702861-L.jpg",
    format: "Paperback",
    subjects: ["History", "Science"],
    shop: masterShops[0],
    shelfLocation: "History · General · Shelf 2",
    condition: "good",
    pricePence: 400,
    valuationConfidence: "high",
    valuationReasons: ["Steady second-hand demand", "Good condition"],
    scannedAt: "2026-07-23T09:18:00Z",
  },
  {
    inventoryId: 3,
    isbn13: "9781529114297",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    publisher: "Vintage",
    publishedYear: 2023,
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781529114297-L.jpg",
    format: "Paperback",
    subjects: ["Fiction", "Contemporary"],
    shop: masterShops[0],
    shelfLocation: "Fiction · T–Z · Shelf 1",
    condition: "like_new",
    pricePence: 500,
    valuationConfidence: "high",
    valuationReasons: ["Very recent title", "Like-new condition"],
    scannedAt: "2026-07-22T16:05:00Z",
  },
  {
    inventoryId: 4,
    isbn13: "9780141182636",
    title: "The Bell Jar",
    author: "Sylvia Plath",
    publisher: "Penguin Classics",
    publishedYear: 2000,
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780141182636-L.jpg",
    format: "Paperback",
    subjects: ["Classics", "Fiction"],
    shop: masterShops[0],
    shelfLocation: "Classics · P · Shelf 4",
    condition: "fair",
    pricePence: 250,
    valuationConfidence: "medium",
    valuationReasons: ["Evergreen classic", "Visible wear"],
    scannedAt: "2026-07-22T14:31:00Z",
  },
  {
    inventoryId: 5,
    isbn13: "9780241341131",
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    publisher: "Penguin",
    publishedYear: 2015,
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780241341131-L.jpg",
    format: "Paperback",
    subjects: ["Psychology", "Health"],
    shop: masterShops[0],
    shelfLocation: "Wellbeing · Shelf 2",
    condition: "good",
    pricePence: 450,
    valuationConfidence: "high",
    valuationReasons: ["Strong second-hand demand", "Good condition"],
    scannedAt: "2026-07-21T12:10:00Z",
  },
  {
    inventoryId: 6,
    isbn13: "9781408855652",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J. K. Rowling",
    publisher: "Bloomsbury",
    publishedYear: 2014,
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781408855652-L.jpg",
    format: "Paperback",
    subjects: ["Children", "Fantasy"],
    shop: masterShops[0],
    shelfLocation: "Children · 9–12 · Shelf 5",
    condition: "good",
    pricePence: 300,
    valuationConfidence: "high",
    valuationReasons: ["Popular children's series", "Good condition"],
    scannedAt: "2026-07-20T10:22:00Z",
  },
];
